// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.test.grpcexample.protoimpl;

public interface APIResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:APIResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response_message = 1;</code>
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string response_message = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();

  /**
   * <code>int32 response_code = 2;</code>
   */
  int getResponseCode();
}
