// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file.proto

package com.test.grpcexample.protoimpl;

public interface DownloadResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DownloadResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes file = 1;</code>
   */
  com.google.protobuf.ByteString getFile();
}
