// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file.proto

package com.test.grpcexample.protoimpl;

public interface DownloadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DownloadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string filename = 1;</code>
   */
  java.lang.String getFilename();
  /**
   * <code>string filename = 1;</code>
   */
  com.google.protobuf.ByteString
      getFilenameBytes();
}
