// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file.proto

package com.test.grpcexample.protoimpl;

public final class File {
  private File() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UploadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UploadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UploadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UploadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DownloadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DownloadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DownloadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DownloadResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nfile.proto\"\035\n\rUploadRequest\022\014\n\004file\030\001 " +
      "\001(\014\"!\n\016UploadResponse\022\017\n\007message\030\001 \001(\t\"#" +
      "\n\017DownloadRequest\022\020\n\010filename\030\001 \001(\t\" \n\020D" +
      "ownloadResponse\022\014\n\004file\030\001 \001(\0142b\n\004file\022)\n" +
      "\006upload\022\016.UploadRequest\032\017.UploadResponse" +
      "\022/\n\010download\022\020.DownloadRequest\032\021.Downloa" +
      "dResponseB(\n\036com.test.grpcexample.protoi" +
      "mplB\004FileP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_UploadRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UploadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UploadRequest_descriptor,
        new java.lang.String[] { "File", });
    internal_static_UploadResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UploadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UploadResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_DownloadRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_DownloadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DownloadRequest_descriptor,
        new java.lang.String[] { "Filename", });
    internal_static_DownloadResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_DownloadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DownloadResponse_descriptor,
        new java.lang.String[] { "File", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
