// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file.proto

package com.test.grpcexample.protoimpl;

public interface UploadResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UploadResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
