// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file.proto

package com.test.grpcexample.protoimpl;

public interface UploadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UploadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes file = 1;</code>
   */
  com.google.protobuf.ByteString getFile();
}
